#!/usr/bin/env perl

# Filter the big list of ephemerides generated by OORB to something smaller
# by skipping lines when the distance from the earth is "large".  Otherwise,
# preserve full detail when close to earth so we can see the close approaches.

use FileHandle;

$lastobj = '';
$fh = undef;
$max_skip = 4;
while (defined($line = <STDIN>)) {
    my ($obj, $mjd, $delta) = split /\s+/, $line;
    if ($obj ne $lastobj) {
        $fh = new FileHandle ">$obj.dat" or die "cannot create $obj.dat";
        print STDERR "Creating $obj.dat.\n";
        $lastobj = $obj;
    }
    if ($delta > .3) {
        if ($skip < $max_skip) {
            $skip++;
            if ($skip == $max_skip) {
                $skip = 0;
            }
        } 
    }
    else {
        $skip = 0;
    }
    if ($skip == 0) {
        print $fh "$mjd $delta\n";
    }
}
$fh->close;
